### ISSUE TITLE
Error...

### ISSUE THREAD

**Issue by mrwert** [thejefflarson/dht#1]
**randombytes(uint8_t *x, uint32_t xlen);**
1..15
x: 6815748, i: 32, xlen: 32
ok 1 - dht allocated correctly, test_dht.c
x: 6815748, i: 32, xlen: 32
x: 7024644, i: 32, xlen: 32
ok 8 - dht allocated correctly, test_dht.c
ok 9 - multiple dhts per process, test_dht.c
ok 10 - hashed 'hello' correctly, test_dht.c
x: 0, i: 8, xlen: 8
x: 0, i: 8, xlen: 8
x: 0, i: 8, xlen: 8
x: 0, i: 8, xlen: 8
x: 0, i: 8, xlen: 8
x: 0, i: 8, xlen: 8
x: 0, i: 8, xlen: 8
x: 0, i: 8, xlen: 8

FreeBSD (clang), DragonFly BSD (gcc).

**Comment by thejefflarson** [comment]
Can you be more specific?
